backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_library:
  name: uploadcare
  config:
    publicKey: 5fff2d77f52b1ab887fc
public_folder: /img

collections:
  - name: "stranky"
    label: "Stranky"
    files:
      - file: "src/pages/index.md"
        label: "Uvodni stranka"
        name: "index"
        fields:
          - {label: 'Upozorneni', name: 'disclaimer', widget: 'markdown', required: false}
          - {label: Uvodni text, name: uvodni_text, widget: object, fields: [{label: Prvni radek, name: firstRow, widget: string, required: false}, {label: Druhy radek, name: secondRow, widget: string, required: false}, {label: Treti radek, name: thirdRow, widget: string, required: false}, {label: Barevne slovo, name: coloredText, widget: string, required: false}]}
          - {label: Uvodni foto, name: uvodni_foto, widget: object, fields: [{label: Obrazek1, name: obrazek1, widget: image}, {label: Obrazek2, name: obrazek2, widget: image}, {label: Obrazek3, name: obrazek3, widget: image}]}
          - {label: Sekce, name: section, widget: object, fields: [{label: Nadpis, name: section_heading, widget: string}, {label: Text, name: section_text, widget: text}, {label: Obrazek, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}

  - name: "novinky"
    label: "Novinky"
    folder: "src/pages/novinky"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Úvod", name: "description", widget: "text"}
      - {label: "Doporučený příspěvek (barevné označení)", name: "featuredpost", widget: "boolean"}
      - {label: "Náhledový obrázek", name: "featuredimage", widget: image}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Tagy", name: "tags", widget: "list"}

  - label: "Projects" 
    name: "projects" 
    folder: "src/pages/novinky" 
    media_folder: 'images' 
    media_library:
      name: uploadcare
      config:
        publickey: 5fff2d77f52b1ab887fc
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "image", widget: "image", allow_multiple: true}
      - label: "Gallery Images"
        name: "images"
        widget: "image"
        options:
          media_library:
            config:
              multiple: true
              previewStep: false
 
