backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "novinky"
    label: "Aktuality"
    folder: "src/pages/aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-post"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Úvod", name: "description", widget: "text"}
      - {label: "Náhledový obrázek", name: "featuredimage", widget: image}
      - {label: "Text", name: "body", widget: "markdown"}
      - {label: "Tagy", name: "tags", widget: "list"}

  - name: galerie
    label: Foto Leto
    folder: "src/pages/galerie/leto"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-post"}
      - {label: "Rok", name: "title", widget: "string", required: true}
      - {label: "Heslo", name: "password", widget: "string", required: true}
      - {label: "Náhledový obrázek", name: "nahledacek", widget: image, required: true}
      - {label: "fotky",
        name: "fotky",
        widget: "image",
        allow_multiple: true,
        media_folder: "static/img/Facebook"}

  - label: "Gallery"
    name: "galleryImages"
    widget: "list"
    folder: "src/pages/galerie/leto"
    create: true
    summary: '{{fields.image}}'
    field: {label: Image, name: image, widget: image}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gallery-post"}
      - {label: "Rok", name: "title", widget: "string", required: true}
      - {label: "Heslo", name: "password", widget: "string", required: true}
      - {label: "Náhledový obrázek", name: "nahledacek", widget: image, required: true}

  - name: velikonoce
    label: Foto Velikonoce
    folder: "src/pages/galerie/velikonoce"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "velikonoce-post"}
      - {label: "Rok", name: "title", widget: "string", required: true}
      - {label: "Heslo", name: "password", widget: "string", required: true}
      - {label: "Náhledový obrázek", name: "nahledacek", widget: image, required: true}
      - {label: "fotky",
        name: "fotky",
        widget: "image",
        allow_multiple: true,
        media_folder: "static/img/Facebook"}

  - name: vylety
    label: Foto vylety
    folder: "src/pages/galerie/vylety"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vylety-post"}
      - {label: "Místo", name: "title", widget: "string", required: true}
      - {label: "Heslo", name: "password", widget: "string", required: true}
      - {label: "Náhledový obrázek", name: "nahledacek", widget: image, required: true}
      - {label: "fotky",
        name: "fotky",
        widget: "image",
        allow_multiple: true,
        media_folder: "static/img/Facebook"}
 
